language: rust
sudo: false
rust:
  - stable
  - beta
  - nightly

script:
  - cargo test
  - cargo run -- --database tests/fixtures/blackscholes.sqlite3 --table static --cores 4

notifications:
  email: false
