language: rust
sudo: false

rust:
  - stable
  - beta
  - nightly

script:
  - cargo test
  - cargo run -- --database tests/fixtures/blackscholes.sqlite3 --table static --cores 4

after_success:
  - curl https://learning-on-chip.github.io/travis/documentation.sh | bash

env:
  global:
    - secure: tZjt7gACSbTp9FJgJlzFQO2rU8oUc1Rrs83qS5O9rh0rc9oe2kfO8vkG/PAr5nqSiPD4NDzrM3w6baJosjifBwFnARS/KpDAuBtH61wEJAOvY2s1pEvO5TM0Aied9l1inrPE5Ywp6x2vi4FVr5ZYUxAkg7YUMxU3TYFvXgbiD3wALVo2pK5xpMvZHKw8v/q8MLCRcw5eX2OC8u4Sf4t2QquTFxd6T3ggrIGTQbSI8IBkHAS8JfNlFWwPcPK2sB29syIJANyI+QSPA2O6zsM2tX621k+lrFtgE5UuiUEEjsCwfzphBbdbpKIj1Xs/Oa5IJwklZ6+NRP4Qy0pBwKN/C89xKQvEgPwUmI2FF9aGLcMyJIP69fx9PXwouG+GROg2nXlznXBz0B5jdeouL5hoMGJL4CC5r5YyatpzEcVcTHbvdfq1gZFKph6v8Fjsxhsqvth3ocLSGTDu+Cas5hk4lowNMr+8tlC2lgn72jMMnWjn4TU2XyQNEFRZZOLiti4PthEjaq/UJc8IhJlTnpMqmen+vWoWFpk7oPOkm7MB2UCBoPFi2Z8216x1hESgiXI2BYjUacghiW0gNR71a7U9e1tRYh5knZCm4j36n3yw7JLfSDF1Z0xHLReat44+wx5kxamQ3VpastDNR+6BVLc5KbuHlqjJjfJmRQmN4GgUodE=

notifications:
  email: false
