language: rust
sudo: false

rust:
  - stable
  - beta
  - nightly

script:
  - cargo test
  - cargo run -- --database tests/fixtures/blackscholes.sqlite3 --table static --cores 4

after_success:
  - curl https://learning-on-chip.github.io/travis/documentation.sh | bash

env:
  global:
    secure: KMfO4vGlvugkrqlI62aXbXIYGgdyV0BuXDzcUndZXg9RCag4PIGfGQzoh212qoLu+5xhmemtju0M7dpIJNS+ZfiZJXEHRdsZBkGqA7k9xVW+9XZE+/LBi3Tvb38+cbxDM7vvM3PfCN8OzEwEC/Eua6Ug0xmc24sQuKfy4tWO/Ls68us0Ri/o474LgzYl1Y+az0BLyEY5CNaXpgggVt/PU1nDe4/B6MoGydK5+mi4jw/YDJrvGeJXgR5K8vFYA7R1saHT3Qk2N5F6AHga5J3hpWHwTKi3iKVLudsQZ0DPkpRSHHekMhgvlWKFibwTcz5OH4wCdstxqp8lEVcypHIuFw1KuCKFM2UoGU4N+RWvo0RWAlkKgDxO74+TzQDc7pBKviZ5CsVL+FoKnzrQMZIfZ/H7Cg3ARYwmOfMHZLP0YbLba7SyDEYUU1tq+sR5ZPF1ULHL86Z3jzcphqU2e0LIb8nsUXFhsTUVpIbDE2zACYCBUF/iTQGYHFszxdpwXE/37W/AAmRF1MAatdYuQL71fJK0KEsjTXPZFcODK0D4C0klNzow/9MdyP7geIcJxYi5S+/APmPXWlUz0cz0vSAZgYJl6Ii9H5dWOMigIvgLp7fUwpLsyufENNfE2MfH1vKmIsuZycEeDVLqndh6thch6TPxSNF0BXvcRG6Yi0Al7UQ=

notifications:
  email: false
